#!/usr/bin/env bash

# Create a regex for a conventional commit.
#convetional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"
convetional_commit_regex="^(feat|fix|build|chore|docs)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   echo -e "\e[32mCommit message meets Conventional Commit standards...\e[0m"
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo -e "\e[31mThe commit message does not meet the Conventional Commit standard\e[0m"
echo "An example of a valid message is: "
echo "  feat(login): add the 'remember me' button"
echo "  or"
echo "  fix: bug fix for DEX-1 base URI fix"
echo "Valid prefix are:"
echo "  fix|feat|docs"
echo "  x.y.z : x == MAJOR; y == MINOR; z == PATCH"
echo "  fix: a commit of the type fix patches a bug in your codebase (this correlates with PATCH in semantic versioning)."
echo "  feat: a commit of the type feat introduces a new feature to the codebase (this correlates with MINOR in semantic versioning)."
echo "  BREAKING CHANGE: a commit that appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in semantic versioning)."
echo "  A BREAKING CHANGE can be part of commits of any type."
echo "If included in the type/scope prefix, breaking changes MUST be indicated by a ! immediately before the : "
echo " example: feat!: New feature added for NGP"
echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1
