# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Semantic Versioning with standard-version

on:
  pull_request:
    types: [ closed ]
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2

    - id: log
      run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
    - if: "contains(steps.log.outputs.message, 'feat!:')"
      run: echo 'feat!:'
    - if: "contains(steps.log.outputs.message, 'feat:')"
      run: echo 'feat:'

    - name: setup git identity user email
      run: git config --global user.email "uddin.md.jashim@gmail.com"
    - name: setup git identity user name
      run: git config --global user.name "Md Jashim Uddin"
    - name: Bump up the pom file
      run: npx @dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml
    - name: Push the tag to trigger a deployment of the new version
      run: git push --follow-tags origin development
